namespace EvDevSharp.Enums;

public enum EvDevAbsoluteAxisCode {
    AbsX             = 0x00,
    AbsY             = 0x01,
    AbsZ             = 0x02,
    AbsRx            = 0x03,
    AbsRy            = 0x04,
    AbsRz            = 0x05,
    AbsThrottle      = 0x06,
    AbsRudder        = 0x07,
    AbsWheel         = 0x08,
    AbsGas           = 0x09,
    AbsBrake         = 0x0a,
    AbsHat0X         = 0x10,
    AbsHat0Y         = 0x11,
    AbsHat1X         = 0x12,
    AbsHat1Y         = 0x13,
    AbsHat2X         = 0x14,
    AbsHat2Y         = 0x15,
    AbsHat3X         = 0x16,
    AbsHat3Y         = 0x17,
    AbsPressure      = 0x18,
    AbsDistance      = 0x19,
    AbsTiltX         = 0x1a,
    AbsTiltY         = 0x1b,
    AbsToolWidth     = 0x1c,
    AbsVolume        = 0x20,
    AbsMisc          = 0x28,
    AbsMtSlot        = 0x2f,
    AbsMtTouchMajor  = 0x30,
    AbsMtTouchMinor  = 0x31,
    AbsMtWidthMajor  = 0x32,
    AbsMtWidthMinor  = 0x33,
    AbsMtOrientation = 0x34,
    AbsMtPositionX   = 0x35,
    AbsMtPositionY   = 0x36,
    AbsMtToolType    = 0x37,
    AbsMtBlobId      = 0x38,
    AbsMtTrackingId  = 0x39,
    AbsMtPressure    = 0x3a,
    AbsMtDistance    = 0x3b,
    AbsMtToolX       = 0x3c,
    AbsMtToolY       = 0x3d,
    AbsMax           = 0x3f,
    AbsCnt           = AbsMax + 1
}
